### ISSUE TITLE
Adapter installation failed

### ISSUE THREAD

**Issue by grobalt** [marc2016/ioBroker.panasonic-comfort-cloud#10]
Fresh installation, first adapter.
Tried to install via other source.

$ ./iobroker url "https://github.com/marc2016/ioBroker.panasonic-comfort-cloud" --debug
install https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/tarball/83359cfb6b4a43575feb14cc9ff7e42ee7e2ef6e
NPM version: 6.14.11
npm install https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/tarball/83359cfb6b4a43575feb14cc9ff7e42ee7e2ef6e --loglevel error --prefix "/opt/iobroker" (System call)
+ iobroker.panasonic-comfort-cloud@1.1.3updated 1 package in 16.506s
18 packages are looking for funding  run `npm fund` for details
upload [5] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/words.js words.js application/javascript
upload [4] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/tsconfig.json tsconfig.json application/json
upload [3] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/style.css style.css text/css
upload [2] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/panasonic-comfort-cloud.png panasonic-comfort-cloud.png image/png
upload [1] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/index_m.html index_m.html text/html
upload [0] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/admin.d.ts admin.d.ts video/mp2t
process exited with code 0

no adapter shown in instances etc.
/opt/iobroker/node_modules/panasonic-comfort-cloud-client exists

**Comment by grobalt** [comment]
Okay, maybe me noob mistake - i could install the adapter now from the adapter list. i expected it is not added to the list .. i expected to show up in instances.

but starting the adapter causes some mistakes:


host.iobroker | 2021-02-15 12:03:26.583 | info | "system.adapter.panasonic-comfort-cloud.0" disabled
-- | -- | -- | --
panasonic-comfort-cloud.0 | 2021-02-15 12:03:26.572 | error | (1597) Unknown error: ServiceError: Bad request.
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.724 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.fanSpeed changed: 4 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.723 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.operationMode changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.721 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.ecoMode changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.720 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.fanAutoMode changed: 1 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.719 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.airSwingUD changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.718 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.airSwingLR changed: 1 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.717 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.temperatureSet changed: 23 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.716 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.operate changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.714 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.guid changed: CS-Z50VKEW+4962603719 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.713 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.fanSpeed changed: 5 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.712 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.operationMode changed: 3 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.711 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.ecoMode changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.710 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.fanAutoMode changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.709 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.airSwingUD changed: 2 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.707 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.airSwingLR changed: 2 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.706 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.temperatureSet changed: 23 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.705 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.operate changed: 1 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.704 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.guid changed: CS-Z35VKEW+4962416397 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.703 | info | (1597) state panasonic-comfort-cloud.0.Büro.fanSpeed changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.701 | info | (1597) state panasonic-comfort-cloud.0.Büro.operationMode changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.700 | info | (1597) state panasonic-comfort-cloud.0.Büro.ecoMode changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.699 | info | (1597) state panasonic-comfort-cloud.0.Büro.fanAutoMode changed: 1 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.697 | info | (1597) state panasonic-comfort-cloud.0.Büro.airSwingUD changed: 1 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.656 | info | (1597) state panasonic-comfort-cloud.0.Büro.airSwingLR changed: 1 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.654 | info | (1597) state panasonic-comfort-cloud.0.Büro.temperatureSet changed: 23 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.653 | info | (1597) state panasonic-comfort-cloud.0.Büro.operate changed: 0 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.652 | info | (1597) state panasonic-comfort-cloud.0.Büro.guid changed: CS-Z25VKEW+4962310685 (ack = false)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.650 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.fanSpeed changed: 4 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.649 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.operationMode changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.648 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.ecoMode changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.647 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.fanAutoMode changed: 1 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.646 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.airSwingUD changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.645 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.airSwingLR changed: 1 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.628 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.temperatureSet changed: 23 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.627 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.operate changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.626 | info | (1597) state panasonic-comfort-cloud.0.Obergeschoss Flur.guid changed: CS-Z50VKEW+4962603719 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.625 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.fanSpeed changed: 5 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.616 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.operationMode changed: 3 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.615 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.ecoMode changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.614 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.fanAutoMode changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.613 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.airSwingUD changed: 2 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.601 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.airSwingLR changed: 2 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.600 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.temperatureSet changed: 23 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.599 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.operate changed: 1 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.598 | info | (1597) state panasonic-comfort-cloud.0.Dachboden.guid changed: CS-Z35VKEW+4962416397 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.596 | info | (1597) state panasonic-comfort-cloud.0.Büro.fanSpeed changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.595 | info | (1597) state panasonic-comfort-cloud.0.Büro.operationMode changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.594 | info | (1597) state panasonic-comfort-cloud.0.Büro.ecoMode changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.588 | info | (1597) state panasonic-comfort-cloud.0.Büro.fanAutoMode changed: 1 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.587 | info | (1597) state panasonic-comfort-cloud.0.Büro.airSwingUD changed: 1 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.586 | info | (1597) state panasonic-comfort-cloud.0.Büro.airSwingLR changed: 1 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.579 | info | (1597) state panasonic-comfort-cloud.0.Büro.temperatureSet changed: 23 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.577 | info | (1597) state panasonic-comfort-cloud.0.Büro.operate changed: 0 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.571 | info | (1597) state panasonic-comfort-cloud.0.Büro.guid changed: CS-Z25VKEW+4962310685 (ack = true)
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.470 | info | (1597) Device Obergeschoss Flur created.
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.467 | info | (1597) Device Dachboden created.
panasonic-comfort-cloud.0 | 2021-02-15 12:03:25.463 | info | (1597) Device Büro created.
panasonic-comfort-cloud.0 | 2021-02-15 12:03:24.465 | info | (1597) Login successful.
panasonic-comfort-cloud.0 | 2021-02-15 12:03:22.502 | info | (1597) starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud, node: v12.20.2, js-controller: 3.1.6

**Comment by grobalt** [comment]
I tried to rename my 3rd unit to "office" instead of Büro but this did not change anything (renamed succesful in android app, new login try with iobroker showed succesful the new name, but same error)

**Comment by marc2016** [comment]
Hi grobalt,

dem Namen der Geräte entnehme ich, dass wir uns auch auf deutsch unterhalten können :-) Kannst Du bitte die Log Ausgaben auf Debug stellen und dann die Ausgabe nochmal hier posten? Dem aktuellen Log kann ich leider nicht entnehmen, warum es zu einem Fehler kommt.

**Comment by grobalt** [comment]
Mh, ich hatte in der Zwischenzeit meinen Raspi platt gemacht und iobroker als neue Installation in einer VM gemacht. Fehler tritt nicht auf ... es tut einfach. Sorry, kann es nicht reproduzieren.
