### ISSUE TITLE
(9344) Service error: . Code=undefined. Stack: ServiceError

### ISSUE THREAD

**Issue by 0x1234567890** [marc2016/ioBroker.panasonic-comfort-cloud#19]
Hey, 
i cant login.  i got a  (9344) Service error: . Code=undefined. Stack: ServiceError

Did anyone know why?

panasonic-comfort-cloud.0 | 2021-06-09 01:10:57.235 | error | at processTicksAndRejections (internal/process/task_queues.js:95:5)
-- | -- | -- | --
panasonic-comfort-cloud.0 | 2021-06-09 01:10:57.235 | error | at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
panasonic-comfort-cloud.0 | 2021-06-09 01:10:57.235 | error | at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
panasonic-comfort-cloud.0 | 2021-06-09 01:10:57.235 | error | at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
panasonic-comfort-cloud.0 | 2021-06-09 01:10:57.235 | error | at ComfortCloudClient.&lt;anonymous&gt; (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:98:30)
panasonic-comfort-cloud.0 | 2021-06-09 01:10:57.235 | error | at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15)
panasonic-comfort-cloud.0 | 2021-06-09 01:10:57.235 | error | at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)
panasonic-comfort-cloud.0 | 2021-06-09 01:10:57.235 | error | (9344) Service error: . Code=undefined. Stack: ServiceError
panasonic-comfort-cloud.0 | 2021-06-09 01:10:57.232 | debug | (9344) Try to handle error.
panasonic-comfort-cloud.0 | 2021-06-09 01:10:56.046 | debug | (9344) Try to login with username mail@xxxxx.de.
panasonic-comfort-cloud.0 | 2021-06-09 01:10:56.008 | info | (9344) starting. Version 1.2.4 in /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud, node: v14.17.0, js-controller: 3.2.16
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.790 | debug | (9344) statesDB connected
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.788 | debug | (9344) States connected to redis: 127.0.0.1:9000
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.780 | debug | (9344) States create User PubSub Client
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.778 | debug | (9344) States create System PubSub Client
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.769 | debug | (9344) Redis States: Use Redis connection: 127.0.0.1:9000
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.766 | debug | (9344) objectDB connected
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.757 | debug | (9344) Objects connected to redis: 127.0.0.1:9001
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.734 | debug | (9344) Objects client initialize lua scripts
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.732 | debug | (9344) Objects create User PubSub Client
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.731 | debug | (9344) Objects create System PubSub Client
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.728 | debug | (9344) Objects client ready ... initialize now
panasonic-comfort-cloud.0 | 2021-06-09 01:10:55.689 | debug | (9344) Redis Objects: Use Redis connection: 127.0.0.1:9001

**Comment by marc2016** [comment]
Hi,

please try again with the new version. See https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/issues/20
