### ISSUE TITLE
Re-Connect after Connection with the iphone

### ISSUE THREAD

**Issue by t1m02k16** [marc2016/ioBroker.panasonic-comfort-cloud#2]
First of all, many thanks for this instance. Super simple and really a great development.
Now to my mistake: If I connect to the iPhone via the Panaconic APP, the connection to the adapter seems to be broken. I don't notice any changes that I make in the Panaconic APP or the Panaconic APP doesn't notice my changes in the iobroker.
greeting

Erstmal vielen lieben Dank für diese instanz. Super einfach und echt eine tolle entwicklung. 
Nun zu meinem Fehler: Verbinde ich mich mit dem Iphone via Panaconic APP, scheint die Verbindung zum Adapter abzureissen. Ich bekomme keine Änderungen mit, die ich in der Panaconic APP durchführe oder die Panaconic APP bekommt meine Änderungen im iobroker nicht mit.
gruss

**Comment by marc2016** [comment]
Hi t1m02k16,

das ist leider richtig. Ich verwende bei dem Adapter einen ganz normalen Login und der wirft leider alle anderen Anwendungen, die mit demselben Login angemeldet sind raus. Ich habe mit einen zweiten Account angelegt und die Geräte über meinen Hauptaccount an den anderen Account freigegeben. Damit würde es funktionieren.

Ich habe bei der Verbindung zwischen Google Home und Panasonic Comfort Cloud gesehen, dass scheinbar OAuth2 unterstützt wird. Mit dieser Technik sollte es auch gehen, allerdings bräuchte ich dazu weitere Informationen von Panasonic und ich bin mir nicht sicher, ob das so einfach möglich ist.

**Comment by t1m02k16** [comment]
Ah okay...
mit einem zweiten Account würde es ja auch gehen... macht ja eigentlich alles iObroker...
Wie füge ich denn in der APP einen Nutzer hinzu. Finde das nicht
Gruß

**Comment by marc2016** [comment]
Wäre erstmal eine mögliche Lösung. Hat er mit dem zweiten Account funktioniert? Ich find das etwas umständlich gelöst von der App...

**Comment by t1m02k16** [comment]
Ja hat wunderbar funktioniert. Heute hatte ich das erste mal einen Auto-LogOut. Kannst du eventuell mit rein bringen, dass der Adapter merkt wenn Werte nicht in die "Cloud" übergeben werden. Dann einfach Neuanmeldung

**Comment by marc2016** [comment]
Ich habe zumindest mal eingebaut, dass er merkt, wenn die Anmeldung abgelaufen ist. Das scheint dann irgendwie nicht richtig zu funktionieren. Ich schaue mir das mal an.
