### ISSUE TITLE
Unknown error: ServiceError.

### ISSUE THREAD

**Issue by t1m02k16** [marc2016/ioBroker.panasonic-comfort-cloud#20]
Moin kann den Adapter nicht mehr nutzen, sobald ich was ändere wird er rot.
![image](https://user-images.githubusercontent.com/19432480/121409943-57af0d00-c962-11eb-848d-b42fd0021bc3.png)

**Comment by t1m02k16** [comment]
Bzw er lässt sich gar nicht mehr starten

**Comment by marc2016** [comment]
Moin. Ist in der Version 1.2.5 behoben. Panasonic fordert jetzt den Parameter User-Agent in den Requests.
Bitte teste es einmal. Danke :-)

**Comment by t1m02k16** [comment]
Also der Login klappt nun wieder, jedoch kann ich nichts steuern...
![image](https://user-images.githubusercontent.com/19432480/121606045-c1581580-ca4d-11eb-9d96-57be7da81089.png)

**Comment by t1m02k16** [comment]
Klappt wieder!!
