### ISSUE TITLE
leider keine Funktion mehr.

### ISSUE THREAD

**Issue by MrP646** [marc2016/ioBroker.panasonic-comfort-cloud#21]
Leider funktioniert der Adapter nicht mehr.
Hier das Log:

panasonic-comfort-cloud.0 | 2021-06-10 17:50:01.078 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
panasonic-comfort-cloud.0 | 2021-06-10 17:50:01.078 | error | at runMicrotasks (&lt;anonymous&gt;)
panasonic-comfort-cloud.0 | 2021-06-10 17:50:01.078 | error | at rejected  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
panasonic-comfort-cloud.0 | 2021-06-10 17:50:01.078 | error | at Object.throw  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
panasonic-comfort-cloud.0 | 2021-06-10 17:50:01.078 | error | at step  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
panasonic-comfort-cloud.0 | 2021-06-10 17:50:01.078 | error | at ComfortCloudClient.&lt;anonymous&gt;  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:133:30)
panasonic-comfort-cloud.0 | 2021-06-10 17:50:01.078 | error | at ComfortCloudClient.handleError  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15)
panasonic-comfort-cloud.0 | 2021-06-10 17:50:01.078 | error | at new ServiceError  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)
panasonic-comfort-cloud.0 | 2021-06-10 17:50:01.078 | error | (984) Service error: . Code=undefined. Stack: ServiceError

Für Hilfe wäre ich sehr dankbar!

Gruß
Dieter

**Comment by t1m02k16** [comment]
Bei mir ebenfalls

**Comment by marc2016** [comment]
Moin. Siehe https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/issues/20
Bitte einmal Version 1.2.5 testen, danke :-)

**Comment by MrP646** [comment]
Hallo, danke für die Hilfe.

Leider keine Änderung mit 1.2.5...



panasonic-comfort-cloud.0 | 2021-06-11 00:17:50.834 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
panasonic-comfort-cloud.0 | 2021-06-11 00:17:50.834 | error | at rejected  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
panasonic-comfort-cloud.0 | 2021-06-11 00:17:50.834 | error | at Object.throw  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
panasonic-comfort-cloud.0 | 2021-06-11 00:17:50.834 | error | at step  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
panasonic-comfort-cloud.0 | 2021-06-11 00:17:50.834 | error | at ComfortCloudClient.&lt;anonymous&gt;  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:98:30)
panasonic-comfort-cloud.0 | 2021-06-11 00:17:50.834 | error | at ComfortCloudClient.handleError  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15)
panasonic-comfort-cloud.0 | 2021-06-11 00:17:50.834 | error | at new ServiceError  (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)
panasonic-comfort-cloud.0 | 2021-06-11 00:17:50.834 | error | (1703) Service error: . Code=undefined. Stack: ServiceError
panasonic-comfort-cloud.0 | 2021-06-11 00:17:49.373 | info | (1703) starting. Version 1.2.5 in  /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud, node:  v12.22.1, js-controller: 3.2.16



Wobei ich nur io-package.json und package.json upgedatet habe.
Waren dass nicht eigentlich mehr Dateien die beim Update eingespielt werden müssen?

Gruß aus Bensheim

Dieter

**Comment by str3000** [comment]
Wollte den Adapter installieren. Auch hier ein Fehler.
Wenn ich die klimaanlage in ioBroker reinmachen könnte wäre echt klasse!

Message ioBroker:
$ ./iobroker url "https://github.com/marc2016/ioBroker./tarball/master" 
install marc2016/ioBroker.#master
NPM version: 7.14.0
npm install marc2016/ioBroker.#master --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code 128
npm ERR! command failed
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/marc2016/ioBroker..gitnpm ERR! git@github.com: Permission denied (publickey).npm ERR! fatal: Could not read from remote repository.npm ERR! npm ERR! Please make sure you have the correct access rightsnpm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2021-06-11T09_08_39_185Z-debug.log
ERROR: host.iobroker01 Cannot install marc2016/ioBroker.#master: 128
ERROR: process exited with code 25

**Comment by mule1972** [comment]
Bei mir funktioniert wieder alles. Vielen Dank für die schnelle Lösung!

**Comment by t1m02k16** [comment]
> Bei mir funktioniert wieder alles. Vielen Dank für die schnelle Lösung!

WIe geht das? :D Ich habe den komplett neuinstalliert und es tut sich nichts....

**Comment by mule1972** [comment]
Ich habe einfach nur per CustomURL-Install im ioBroker den Adapter installiert und es lief alles.

**Comment by t1m02k16** [comment]
Habe definitiv die neuste Version. Der Login scheint auch zu funktionieren. Ändere ich jedoch einen Zustand passiert nichts.

![image](https://user-images.githubusercontent.com/19432480/121801075-c1b30500-cc35-11eb-8c7f-9bc0e5ae878a.png)

![image](https://user-images.githubusercontent.com/19432480/121801084-cbd50380-cc35-11eb-90df-c3a05a41195a.png)

**Comment by marc2016** [comment]
Aus irgendeinem Grund scheint die Guid leer zu sein. Damit hatte ich schon mal Probleme, weil Panasonic die API umgestellt hat. Da muss ich dann nochmal ran, dass das Feld aktualisiert wird, wenn es leer ist. Eine schnelle Lösung wäre es, wenn Du das Gerät einmal löscht.

**Comment by mule1972** [comment]
Mhmm merkwürdig, bei mir sind bei 3 Anlagen die GUIDs vorhanden?!

**Comment by marc2016** [comment]
> Mhmm merkwürdig, bei mir sind bei 3 Anlagen die GUIDs vorhanden?!

Hast Du denn auch Probleme?

**Comment by t1m02k16** [comment]
@marc2016  Meinst du das Objekt in iobroker? Falls ja, habe ich schon. Mehrfach sogar Instanz und Adapter deinstalliert/gelöst. Mich wundert es, dass es bei @mule1972 funktioniert

**Comment by marc2016** [comment]
Ich prüfe einmal, ob die API wieder angepasst wurde. Komme ich hoffentlich heute Abend zu.

**Comment by mule1972** [comment]
> 
> 
> > Mhmm merkwürdig, bei mir sind bei 3 Anlagen die GUIDs vorhanden?!
> 
> Hast Du denn auch Probleme?

Bei mir funktioniert alles: Login, Statusanzeige und gerade probiert: Auch die Ansteuerung.

**Comment by MrP646** [comment]
> 
> 
> Ich habe einfach nur per CustomURL-Install, wie bei vorherigen Updates, im ioBroker den Adapter installiert und es lief alles. Was meinst Du denn mit „es tut sich nichts“? Was steht denn im Log?

Wie hast du das gemacht?
Ich habe den Adapter zum Test deinstalliert und jetzt bekomme ich ihn nicht mehr installiert.
Ich dachte ich bekomme den Adapter über den ioBroker>Adapter>installieren aus eigener URL>npm i iobroker.panasonic-comfort-cloud installiert.
Das gibt aber eine Fehlermeldung wegen einer Zugriffsverletzung.
Ich Steh gerade echt auf dem Schlauch...

Das Log besagt:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'i/ioBroker.npm#master',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose config Skipping project config: /opt/iobroker/.npmrc. (matches userconfig)
5 verbose npm-session 46f47ab9bfb0770b
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for github:i/ioBroker.npm#master Error while executing:
8 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t ssh://git@github.com/i/ioBroker.npm.git
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData Host key verification failed.
8 silly fetchPackageMetaData fatal: Konnte nicht vom Remote-Repository lesen.
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
8 silly fetchPackageMetaData und das Repository existiert.
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData exited with error code: 128
9 timing stage:rollbackFailedOptional Completed in 5ms
10 timing stage:runTopLevelLifecycles Completed in 18646ms
11 verbose stack Error: exited with error code: 128
11 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
11 verbose stack     at ChildProcess.emit (events.js:314:20)
11 verbose stack     at maybeClose (internal/child_process.js:1022:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
12 verbose cwd /opt/iobroker
13 verbose Linux 3.10.105
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "i/ioBroker.npm#master" "--loglevel" "error" "--prefix" "/opt/iobroker"
15 verbose node v12.22.1
16 verbose npm  v6.14.12
17 error Error while executing:
17 error /usr/bin/git ls-remote -h -t ssh://git@github.com/i/ioBroker.npm.git
17 error
17 error Host key verification failed.
17 error fatal: Konnte nicht vom Remote-Repository lesen.
17 error
17 error Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
17 error und das Repository existiert.
17 error
17 error exited with error code: 128
18 verbose exit [ 1, true ]

Ich hoffe Ihr könnt mir helfen!?!

**Comment by marc2016** [comment]
Verwendest Du als URL "npm i iobroker.panasonic-comfort-cloud"?
Für die manuelle Installation ist die korrekte URL "https://github.com/marc2016/ioBroker.panasonic-comfort-cloud". Bitte versuch es einmal damit, wenn Du es nicht schon getan hast.

**Comment by marc2016** [comment]
@t1m02k16 Ich habe es nochmal geprüft und hatte noch einen Fehler in der Geräteerstellung. Ich muss die GUID, wegen der API Änderung, anders beziehen und hier war noch ein Fehler. Ich kann mir nicht erklären, warum dieser Fehler nicht vorher aufgefallen ist. Ich konnte es bei mir jetzt nachstellen und habe eine neue Version veröffentlicht -> 1.2.6
Bitte testen, danke :-)

**Comment by t1m02k16** [comment]
@marc2016 MIt der 1.2.6 klappt wieder!!!!
Vielen Dank für den schnellen Fix! Dank dir und deinem Adapter kann ich wieder schlafen ^^

**Comment by MrP646** [comment]
@marc2016 Manchmal sieht man den Wald vor lauter Bäumen nicht. Vielen Dank für den Hilfreichen Tip.
Mit 1.2.6 läuft wieder alles.

Vor allem vielen Dank für den Tollen Adapter und deine Arbeit!
Der Adapter ist Gold wert! ;)
Gruß aus Bensheim

Dieter

**Comment by str3000** [comment]
Hallo marc2016,
ja das mit dem falschen Link hatte ich bereits bemerkt. Danach hatte ich Verbindung, konnte aber nichts ansteuern.
Ich mache mal das update und prüfe es dann.
In Zukunft schreibe auch auch rein wenn ein Problem nicht mehr besteht - versprochen :-)
Ich hatte nur eine weitere Probleme mit:
- js-Controller und HM-IP
- Material design
War leider kein erfolgreiches WE.

**Comment by str3000** [comment]
Hallo marc2016,
ich bin Anfänger bei den Adaptern und bei der Programmierung.
Ich habe den Adapter gelöscht und wieder installiert. Somit war neuste Version vorhanden.
Mit "tarball" habe ich nichts gemacht (auch nicht installiert). 

Mit dem neuen Adapter konnte ich die Klimaanlage anschalten.
TOP!
Dann bin ich in die App und habe mich dort eingeloggt.
Vermutlich bin ich bei ioBroker dann rausgeflogen (kann ja immer nur einer eingeloggt sein - furchtbar)
Keine Steuerung mehr im ioBroker dann mehr möglich.
Weiss aber nicht ob das so gewollt ist. Instanz neustart hat das Problem behoben.
(Im Refreshintervall stand zu dem zeitpunkt nichts. Habe nun 5 eingetragen)
Gibt es bei Panasonic eine Lösung zu dem Probelm das sich nur einer einloggen kann?
Auch nach eintragen von einem Wert in refreshintervall bleibt das Problem bestehen.

Hat jemand eine Visu erstellt und kann die bereitstellen? 


hier Fehlermeldungen:


panasonic-comfort-cloud.0 | 2021-06-14 09:04:32.228 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
panasonic-comfort-cloud.0 | 2021-06-14 09:04:32.228 | error | at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
panasonic-comfort-cloud.0 | 2021-06-14 09:04:32.228 | error | at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
panasonic-comfort-cloud.0 | 2021-06-14 09:04:32.228 | error | at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
panasonic-comfort-cloud.0 | 2021-06-14 09:04:32.228 | error | at ComfortCloudClient.&lt;anonymous&gt;  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:206:30)
panasonic-comfort-cloud.0 | 2021-06-14 09:04:32.228 | error | at ComfortCloudClient.handleError  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15)
panasonic-comfort-cloud.0 | 2021-06-14 09:04:32.228 | error | at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)
panasonic-comfort-cloud.0 | 2021-06-14 09:04:32.228 | error | (16622) Service error: Token expires. Code=4100. Stack: ServiceError: Token expires
panasonic-comfort-cloud.0 | 2021-06-14 09:04:31.072 | info | (16622) state panasonic-comfort-cloud.0.Schlafzimmer.operate changed: 0 (ack = false)

**Comment by MrP646** [comment]
@str3000 Da kann ich dir sogar weiterhelfen.
Du kannst nur einen Account parallel nutzen. Du kannst deine Anlage aber an verschiedenen Accounts betreiben.
Also ein Benutzer kann sich nur an einem Telefon eintragen. Am 2. Telefon würde das 1. Telefon abgemeldet.
Du kannst aber für jedes Telefon einen eigenen Nutzer anlegen und die können dann parallel laufen.
Einfach für den ioBroker einen Eigenen Account (am Telefon) erstellen und dann im ioBroker anmelden. Dann kannst du mehrere Telefone und ioBroker parallel betreiben.
lG
Dieter
