### ISSUE TITLE
Token expired

### ISSUE THREAD

**Issue by git2206** [marc2016/ioBroker.panasonic-comfort-cloud#23]
Hi,

your adapter was working well since few days... i saw in the log file - token expired.... there is a new app....
Can you fix this or what i can do - i can create a new token by myself?

THX
Flo

**Comment by pseudoreal247** [comment]
I got the message "Service error: New version app has been published. Code=4106.", too

**Comment by marc2016** [comment]
Hi, 

I have to update the X-APP-Version in the http request. I will try to fix it today.

**Comment by t1m02k16** [comment]
![image](https://user-images.githubusercontent.com/19432480/126066087-6138a36d-c385-40c0-a97d-16440f0c7a05.png)
 Gleicher Fehler oder?

**Comment by marc2016** [comment]
Ja derselbe Fehler. Kümmere mich drum.

**Comment by marc2016** [comment]
Fixed in the new version 1.2.7
Please try it out.

**Comment by pseudoreal247** [comment]
tested with 1.2.8 and it works

**Comment by t1m02k16** [comment]
Klappt! Vielen Dank!
PS: du musst den Versionsnamen noch anpassen

**Comment by git2206** [comment]
Super, funktioniert wieder!
DANKE!!!!!
