### ISSUE TITLE
Stack: ServiceError at new ServiceError 

### ISSUE THREAD

**Issue by Kirdan62** [marc2016/ioBroker.panasonic-comfort-cloud#25]
Folgende Fehlermeldung bekomme ich vom Adapter (Version 1.2.7), mein System ist mit allen Grundadaptern auf dem aktuellen Stand.

`Service error: . Code=undefined. Stack: ServiceError at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:133:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by marc2016** [comment]
Hi, sorry for the late reply :-( 
it looks like the same issue as #27 I will try to fix it in this issue and close this one.
