### ISSUE TITLE
panasonic-comfort-cloud.0.xxx.operationMode" which expects a array

### ISSUE THREAD

**Issue by bandimuc** [marc2016/ioBroker.panasonic-comfort-cloud#26]
Hi Marc,

this might by an easy thing but when I create a Blockly Skript to add the AC to a workflow I always get an error reported 
javascript.0
at processTimers (internal/timers.js:497:7)
at listOnTimeout (internal/timers.js:556:17)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1497:29)
at Object.setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1439:20)
You are assigning a object to the state "panasonic-comfort-cloud.0.xxx.operationMode" which expects a array. Please fix your code to use a array or change the state type to object. This warning might become an error in future versions.

To turn on or off the AC unit I need to change the setting from 0 to 1 or back on the operate variable if I'm not mistaken.

I have tried that as string or math number but both came up with the same error.

Many thanks in advance.

**Comment by marc2016** [comment]
Hi, sorry for the late reply :-(
the error says that I am using the wrong type for operationMode state. I will try to change it to the correct type.
