### ISSUE TITLE
Stack: ServiceError at new ServiceError

### ISSUE THREAD

**Issue by mule1972** [marc2016/ioBroker.panasonic-comfort-cloud#27]
Hi Marc,

first once again thank you for developing this adapter.
I am getting the following error when running your adapter. I did install the latest version from your git master. Anything I could do?

`Service error: . Code=undefined. Stack: ServiceError at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:163:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:94:5)`

**Comment by marc2016** [comment]
Hi, you're welcome :-)

please set the log level to debug. Maybe we get more information.

**Comment by marc2016** [comment]
@Kirdan62 has the same issue

**Comment by mule1972** [comment]
Hi Marc,

besides the already posted error message the adapter now crashes reguarly with "UNCAUGHT_EXCPTION". Even an uninstall of the adapter and new install from github did not solve the issue.

Debug Log:
`<html><body>


panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.992 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.991 | info | terminating
panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.991 | info | cleaned everything up...
panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.972 | error | Exception-Code: 5005: Adapter Communication error
panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.972 | error | ServiceError:  Adapter Communication error     at new ServiceError  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)     at ComfortCloudClient.handleError  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15)     at ComfortCloudClient.<anonymous>  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:163:30)     at step  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)     at Object.throw  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)     at rejected  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)     at processTicksAndRejections (internal/process/task_queues.js:94:5)
panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.971 | error | unhandled promise rejection: Adapter Communication error
panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.970 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.058 | debug | Device info from group C452117590, BueroCL.
panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.057 | debug | Device info from group C741304199, Schlafen.
panasonic-comfort-cloud.0 | 2021-11-29 16:49:27.055 | debug | Device info from group C377577951, Wohnen.
panasonic-comfort-cloud.0 | 2021-11-29 16:49:25.015 | debug | Create devices.
panasonic-comfort-cloud.0 | 2021-11-29 16:49:25.009 | info | Login successful.


</body>
</html>`

**Comment by marc2016** [comment]
Apparently an error occurs after getting device info of BueroCL. Unfortunately, the information about the error is not written to the log. I updated the adapter to version 1.2.9 and added a more detailed log (hopefully). 
Please install the new version, try it again and post the error message please.

Thank you!

**Comment by mule1972** [comment]
Thanks again for your support. I installed the new version and it did not crash anymore, but once again did throw the "Service error":

`<html><body>


panasonic-comfort-cloud.0 | 2021-12-05 23:05:08.775 | debug | Device creation completed.
-- | -- | -- | --
panasonic-comfort-cloud.0 | 2021-12-05 23:05:08.775 | error | Service  error: Adapter Communication error. Code=5005. Stack: ServiceError:  Adapter Communication error     at new ServiceError  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)     at ComfortCloudClient.handleError  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15)     at ComfortCloudClient.<anonymous>  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:163:30)     at step  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)     at Object.throw  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)     at rejected  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)     at processTicksAndRejections (internal/process/task_queues.js:94:5)
panasonic-comfort-cloud.0 | 2021-12-05 23:05:08.774 | debug | Try to handle error.
panasonic-comfort-cloud.0 | 2021-12-05 23:04:59.185 | error | Service  error: Adapter Communication error. Code=5005. Stack: ServiceError:  Adapter Communication error     at new ServiceError  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)     at ComfortCloudClient.handleError  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15)     at ComfortCloudClient.<anonymous>  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:163:30)     at step  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)     at Object.throw  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)     at rejected  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)     at processTicksAndRejections (internal/process/task_queues.js:94:5)
panasonic-comfort-cloud.0 | 2021-12-05 23:04:59.181 | debug | Try to handle error.
panasonic-comfort-cloud.0 | 2021-12-05 23:04:58.308 | debug | Device info from group C452117590, BueroCL.
panasonic-comfort-cloud.0 | 2021-12-05 23:04:58.307 | debug | Device info from group C741304199, Schlafen.
panasonic-comfort-cloud.0 | 2021-12-05 23:04:58.296 | debug | Device info from group C377577951, Wohnen.
panasonic-comfort-cloud.0 | 2021-12-05 23:04:56.816 | debug | Create devices.
panasonic-comfort-cloud.0 | 2021-12-05 23:04:56.815 | info | Login successful.
panasonic-comfort-cloud.0 | 2021-12-05 23:04:55.009 | debug | Try to login with username cnoack@web.de.
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.909 | info | starting. Version 1.2.9 in /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud, node: v12.14.1, js-controller: 3.3.21
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.385 | debug | statesDB connected
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.384 | debug | States connected to redis: 127.0.0.1:9000
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.325 | debug | States create User PubSub Client
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.324 | debug | States create System PubSub Client
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.312 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.310 | debug | objectDB connected
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.304 | debug | Objects connected to redis: 127.0.0.1:9001
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.267 | debug | Objects client initialize lua scripts
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.266 | debug | Objects create User PubSub Client
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.265 | debug | Objects create System PubSub Client
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.263 | debug | Objects client ready ... initialize now
panasonic-comfort-cloud.0 | 2021-12-05 23:04:54.209 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001


</body>
</html>`

**Comment by marc2016** [comment]
The message extracted from the android app for code 5005 says "Return to this application after completing the wireless network settings to continue the setup." (in German: "Bitte kehren Sie zu dieser Anwendung zurück, nachdem Sie die Einstellungen zum drahtlosen Netzwerk vorgenommen haben, um mit dem Einrichten fortzufahren.").
Can you control the device with the iOS or Android app? 
Last month the app showed me a similar message. I had to completely disconnect the device from the power so that the LEDs no longer blinking. After I switched the fuse back on, everything worked normally.

**Comment by mule1972** [comment]
Same issue as you described: Two of my Panasonic WLAN adapters lost the connection to my WLAN. After powering off and powering on the corresponding air conditioners again the WLAN adapters immediately connected to my WLAN again. Everyting is fine now. Seems that the Panasonic WLAN adapters have a reconnect issue.

Once again thanks for your support!
