### ISSUE TITLE
Unsupported platform

### ISSUE THREAD

**Issue by DerGrafausB** [marc2016/ioBroker.panasonic-comfort-cloud#28]
$ iobroker url https://github.com/marc2016/ioBroker.panasonic-comfort-cloud --host ioBroker --debug

install marc2016/ioBroker.panasonic-comfort-cloud#b670956a90504dc4c6f2febd2695f175330077a7

NPM version: 6.14.15

npm install marc2016/ioBroker.panasonic-comfort-cloud#b670956a90504dc4c6f2febd2695f175330077a7 --prefix "/opt/iobroker" (System call)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@^1.0.7 (node_modules/iobroker.info/node_modules/osx-temperature-sensor):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/has-binary2/package.json'

npm WARN @zwave-js/winston-daily-rotate-file@4.5.6-1 requires a peer of winston@^3.3.4 but none is installed. You must install peer dependencies yourself.

+ iobroker.panasonic-comfort-cloud@1.2.9

updated 1 package in 19.977s

92 packages are looking for funding

run `npm fund` for details

upload [4] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/words.js words.js application/javascript

upload [3] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/style.css style.css text/css

upload [2] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/panasonic-comfort-cloud.png panasonic-comfort-cloud.png image/png

upload [1] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/index_m.html index_m.html text/html

upload [0] panasonic-comfort-cloud.admin /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/admin/admin.d.ts admin.d.ts video/mp2t

Process exited with code 0

**Comment by marc2016** [comment]
Was the installation of the adapter successful?
