### ISSUE TITLE
adapter legt keine Datenpunkte an 

### ISSUE THREAD

**Issue by arteck** [marc2016/ioBroker.panasonic-comfort-cloud#3]
kann ich den adapter nu per script ansprechen oder warum hab e9ich keine Datenpunkte angelegt bekommen nach dem start 

![grafik](https://user-images.githubusercontent.com/6681528/86528993-49808300-bead-11ea-8073-30119178c16f.png)

![grafik](https://user-images.githubusercontent.com/6681528/86529005-63ba6100-bead-11ea-8929-e434850050f6.png)

**Comment by marc2016** [comment]
Hi arteck,

hast Du in der Adapter Konfiguration Zugangsdaten zu einem Account hinterlegt?

**Comment by t1m02k16** [comment]
@arteck Hatte genau das gleich Problem. Einfach Adapter neustarten. Dann werden die Punkte angelegt
