### ISSUE TITLE
No connection to device or service

### ISSUE THREAD

**Issue by chriz1985** [marc2016/ioBroker.panasonic-comfort-cloud#30]
Hi Marc,

the adapter was working really fine, thanks for that.
Since yesterday I receive the messege in the protocoll:

Service error: . Code=undefined. Stack: ServiceError at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:98:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at processTicksAndRejections (internal/process/task_queues.js:95:5)
--
 
Do you have an idea what could be wrong?
Version is 2.01, 
Node.js v14.19.1

**Comment by chriz1985** [comment]
Updated to 2.02 and it's working again!

**Comment by marc2016** [comment]
Hi Chriz,
you‘re welcome :-)
I got the same error yesterday and fixed it 👍🏻

**Comment by chriz1985** [comment]
Thanks, amazing!

Mobil gesendet
________________________________
