### ISSUE TITLE
Repeated errors when devices are off

### ISSUE THREAD

**Issue by jensb** [marc2016/ioBroker.panasonic-comfort-cloud#32]
**Describe the bug**  
My climate control is behind a switch to reduce standby current (~8W, 24/7) of the Panasonic devices.
This causes the iobroker adapter to constantly restart and spam the logs with error message every five minutes:

Service error: Request failed with status code 403. Code=undefined. Stack: ServiceError: Request failed with status code 403 at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:133:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5)

**To Reproduce**  
1. Turn Panasonic devices off (really off, hard switch)
2. Start adapter
3. Watch logs

**Expected behavior**  
If the devices are off / not reachable, can we have an option (or default) to *not* regard this as an error, and simply silently try to reconnect periodically?

**Versions:**  
Raspbian 64bit, Node: v14.19.0, js-controller: 4.0.23, adapter: 2.0.2

Thank you!

**Comment by Kirmesboxer24** [comment]
I am getting the same error, but my devices are reachable by the Comfort Cloud App and operating normal besides of that. In the app, there have been a notice about a cloud downtime, but I dismissed it and now it is gone. 
So, this seems to be a general issue. 

Message from my log is exactly the same:
Service error: Request failed with status code 403. Code=undefined. Stack: ServiceError: Request failed with status code 403 at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:176:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:98:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by mtb-z** [comment]
Same error here. Devices are reachable and can be controlled via the ComfortCloud App. 
When the error appeared the first time (two or three days ago), I had also issues to connect to my devices via the ComfortCloud app. It seemed that the cloud was not reachable for about 8 hrs or so. Maybe Panasonic changed something at their end? 
Now connection via the ComfortCloud app works again but not via the iobroker adapter. Also tried to restart the instance.

**Comment by marc2016** [comment]
Hi everyone

this is about two different points. The question from @jensb is da feature request and the other two messages from @Kirmesboxer24 and @mtb-z are a bug.
@Kirmesboxer24 @mtb-z i got the same error few days ago and fixed it in version 2.0.4. Please try this version and give me a feedback.

@jensb maybe I can add a reachable state for the devices and remove the error. I will try to add the function .

**Comment by mtb-z** [comment]
> Hi @marc2016 , sorry for mixing things up. Everything is up and working again with 2.0.4! Thanks a lot!

Same here. Works well now. Thank you for your efforts!

**Comment by marc2016** [comment]
@jensb I added a new state 'connected' for the devices.
