### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by str3000** [marc2016/ioBroker.panasonic-comfort-cloud#34]
Update 26.08
Zwei der vier Geräte hatten kein Wlan empfang und lassen sich nun wieder Steuern.
Evtl. hat sich dadurch das Problem erledigt.
Instanz geht trotzdem noch nicht auf grün.

Hallo,
seit kurzem bekomme ich eine Störung beim starten der Instanz.
Fehlermeldungen siehe unten.

Was ist neu:
In der Cloud habe ich eine Wärmepumpe hinzugefügt.
Bei dem ioBroker User hatte ich die hinzugefügt, gelöscht und wieder hinzugefügt.
Fehler ist immer geblieben.
Ob es damit zusammenhängt kann ich nicht sagen.
Habe 4 Klimageräte und eine Wärmepumpe angeschlossen.

Eine Idee woran das leigen könnte?

Versionen: alles aktuell aus Beta Repo (aussser Node.js)
panasonic-comfort-cloud.0: V2.0.4

Plattform
    linux
Betriebssystem
    linux
Architektur
    x64
CPUs
    4
Geschwindigkeit
    3000 MHz
Modell
    11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
RAM
    6 GB
System-Betriebszeit
    00:40:37
Node.js
    v16.16.0 (Es gibt eine neuere Version: v16.17.0)
NPM
    8.11.0

Fehlermeldungen:
Service  error: Request failed with status code 500. Code=undefined. Stack:  ServiceError: Request failed with status code 500    at new ServiceError   (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)     at ComfortCloudClient.handleError  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:178:15)     at ComfortCloudClient.<anonymous>  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:165:30)     at step  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)     at Object.throw  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)     at rejected  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)     at processTicksAndRejections  (node:internal/process/task_queues:96:5)
--
panasonic-comfort-cloud.0 | 2022-08-24 11:49:08.926 | error | Service  error: Request failed with status code 500. Code=undefined. Stack:  ServiceError: Request failed with status code 500    at new ServiceError   (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28)     at ComfortCloudClient.handleError  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:178:15)     at ComfortCloudClient.<anonymous>  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:165:30)     at step  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)     at Object.throw  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)     at rejected  (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)     at processTicksAndRejections  (node:internal/process/task_queues:96:5)

**Comment by marc2016** [comment]
Wärmepumpen funktionieren leider nicht mit dem Adapter.
Mit der Version 2.3.0 sollte es jetzt aber gehen, dass der Adapter funktioniert, auch wenn ein Gerät einen Fehler hat oder nicht richtig erkannt wird.
