### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by Muskelkatermann** [marc2016/ioBroker.panasonic-comfort-cloud#37]
Since yesterday the adapter stopped working.

In iobroker log I can see this error:
`Service error: Request failed with status code 401. Code=undefined. Stack: ServiceError: Request failed with status code 401 at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:20:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:178:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:100:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at processTicksAndRejections (internal/process/task_queues.js:95:5)`

I verified my user credentials and changed them in admin once and back to maybe generate a new auth token or something.
The adapter has been working fine since I installed it a couple of months ago. Nothing has changed on my side if the system as far as i'm concerned. Maybe panasonic activeted some kind of bot mitigation? Then others should habe the same problem.

Comfort Cloud App works just fine.

Adapter Version 2.0.4
Node 14.19.0
js-controller 3.3.22

**Comment by Aprilia1982** [comment]
It's already fixed in 2.0.6 -> [https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/issues/360]
Currently you need to install form Github

**Comment by Muskelkatermann** [comment]
Fix confirmed. Thanks a lot.
