### ISSUE TITLE
Datenpunkt für FanSpeed

### ISSUE THREAD

**Issue by eliasgraf** [marc2016/ioBroker.panasonic-comfort-cloud#4]
Hi Marc,

super Adapter der auch, vor allem für sein 0.1 Stadium super läuft :-)
Leider vermisse ich noch die Einstellung für den Fan Speed die ja in der App auch verfügbar ist, kannst du die noch hinzufügen?

Vielen Dank und Gruß 
Elias

**Comment by t1m02k16** [comment]
GIbt es doch... "Auto" "Powerfull" "Quiet"

**Comment by eliasgraf** [comment]
Hi! Jein das ist ja nur ne "zusätzliche" Betriebsart aber man kann auf jeden Fall auch den FanSpeed getrennt einstellen.
Auf der Fernbedienung ist das ja auch ne zusätzliche Taste :-)
Das was ich im Code verstehe ist das am Anfang im "import" auch ziemlich weit unten als FanSpeed vorhanden oder? Wird dann blos später nicht als Datenpunkt angelegt? ... sorry kann bisschen coden aber wirklich nur bisschen :-(
Gruß Elias

**Comment by marc2016** [comment]
Hi Elias,

Danke für das Feedback! Stimmt, hatte ich mal vorgesehen, aber ich weiß gar nicht mehr, warum ich es nicht umgesetzt habe. Ist jetzt mit der Version 1.1.0 eingebaut und ich habe es gerade getestet. Bitte auch einmal testen, danke! :-)

**Comment by eliasgraf** [comment]
Musste den Adapter einmal löschen und wieder Installieren damit der Datenpunkt angelegt wurde, funktioniert dann aber super, vielen vielen Dank!
