### ISSUE TITLE
Cloud connected -> But no device visible in objects?

### ISSUE THREAD

**Issue by pfostenberg** [marc2016/ioBroker.panasonic-comfort-cloud#46]
Hi

I want to use the Adapter.
Created a second user and with the web UI I can login and see all the data.

On IOBroker I can also connect. all successfully.
But I do not see any data?
I increased log level to debug...

I have a heatpump ..
also tried use github and different API versions.

Can someone help?

BR

Andreas

----log 

panasonic-comfort-cloud.0 | 2023-09-08 00:32:27.000 | debug | refreshIntervalInMilliseconds=60000
panasonic-comfort-cloud.0 | 2023-09-08 00:32:26.999 | debug | setupRefreshTimeout
panasonic-comfort-cloud.0 | 2023-09-08 00:32:26.996 | debug | Device creation completed.
panasonic-comfort-cloud.0 | 2023-09-08 00:32:25.826 | info | state panasonic-comfort-cloud.0.info.connection changed: true (ack = true)
panasonic-comfort-cloud.0 | 2023-09-08 00:32:25.782 | debug | Create devices.
panasonic-comfort-cloud.0 | 2023-09-08 00:32:25.778 | info | Login successful.
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.788 | debug | Try to login with username wp_iob@....
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.785 | debug | Use configured AppVersion from Github 1.18.2.
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.782 | info | Loaded app version from GitHub: 1.18.2
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.765 | info | state panasonic-comfort-cloud.0.info.connection changed: false (ack = true)
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.428 | info | starting. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud, node: v18.17.0, js-controller: 4.0.24
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.150 | debug | States connected to redis: 127.0.0.1:9000
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.079 | debug | States create User PubSub Client
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.077 | debug | States create System PubSub Client
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.054 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
panasonic-comfort-cloud.0 | 2023-09-08 00:32:23.008 | debug | Objects connected to redis: 127.0.0.1:9001
panasonic-comfort-cloud.0 | 2023-09-08 00:32:22.994 | debug | Objects client initialize lua scripts
panasonic-comfort-cloud.0 | 2023-09-08 00:32:22.946 | debug | Objects create User PubSub Client
panasonic-comfort-cloud.0 | 2023-09-08 00:32:22.943 | debug | Objects create System PubSub Client
panasonic-comfort-cloud.0 | 2023-09-08 00:32:22.917 | debug | Objects client ready ... initialize now
panasonic-comfort-cloud.0 | 2023-09-08 00:32:22.845 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001

**Comment by marc2016** [comment]
Hi Andreas,

This Adapter does not support headhunts, sorry :-(
I started a new adapter for this, but the progress was very low…
https://github.com/marc2016/panasonic-aquarea-client
