### ISSUE TITLE
Service error: Request failed with status code 400

### ISSUE THREAD

**Issue by OnkelFD** [marc2016/ioBroker.panasonic-comfort-cloud#47]
Seit gestern lässt sich der Adapter leider nicht mehr verbinden und im Log erscheint dieser Fehler.
An den Einstellungen wurde nichts verändert und die Anlage ist über WiFi erreichbar. 

Service error: Request failed with status code 400. Code=undefined. 
Stack: ServiceError: Request failed with status code 400 
at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28) 
at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:184:15) 
at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:106:30) 
at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) 
at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) 
at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) 
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by pfostenberg** [comment]
same on my side... any idear?

**Comment by OnkelFD** [comment]
Heute Nacht wurden Wartungen am Panasonic Server durchgeführt, was eventuell zu Inkompatibilität des Adapters geführt hat.
Habe auch schon verschiedene API Versionen ausprobiert was aber nicht zum Erfolg geführt hat.

**Comment by Sansibarr** [comment]
Same here, scheint ein generelles Problem zu sein...

**Comment by marc2016** [comment]
Es scheint nicht an der AppVersion zu liegen. Es scheint sich für den Login irgendwas im Aufruf geändert zu haben. 
Ich versuche das Problem zu lösen.

**Comment by marc2016** [comment]
Der REST Aufruf braucht seit neustem drei neue Header Parameter:
`X-APP-TIMESTAMP:1
X-APP-NAME:Comfort Cloud
X-CFC-API-KEY:Comfort Cloud`
Muss ich morgen ergänzen und dann eine neue Version bauen.

**Comment by marc2016** [comment]
Ich hatte noch einen Bug beim Abrufen der Geräte-Informationen. Leider sind meine beiden Accounts jetzt 24h gesperrt und ich kann es nicht abschließend testen. Der Fehler sollte aber behoben sein und ich kann hoffentlich morgen Abend eine neue Version veröffentlichen 🤗

**Comment by OnkelFD** [comment]
vielen dank bei mir läuft es mit der v2.2.1 👍

**Comment by marc2016** [comment]
Super, danke fürs testen 👍🏻
Dann kann ich die Version gleich veröffentlichen.

**Comment by superemil70** [comment]
Besten Dank für das schnelle Umsetzung @marc2016 
Gerade v2.2.2 aufgespielt. Läuft wieder

**Comment by Kirmesboxer24** [comment]
v2.2.2 works like a charm. Thank you!

**Comment by ManuelBu96** [comment]
Hallo zusammen,
habe gerade die Version 2.2.2 installiert und es kommt immer noch ein Fehler. Die Verbindung zur Cloud lässt sich nicht aufbauen.
Muss ich noch etwas anderes anpassen/ändern?

Hi,
i have installed the version 2.2.2 and still have some issues. The connection to the cloud could not be established. Do I need to adjust/change anything else?

`Service error: Request failed with status code 401. Code=undefined. Stack: ServiceError: Request failed with status code 401 at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:184:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:106:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at processTicksAndRejections (internal/process/task_queues.js:97:5)`
