### ISSUE TITLE
Please fix errors reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [marc2016/ioBroker.panasonic-comfort-cloud#48]
❗ [E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
❗ [E605] No actual year found in copyright. Please add "Copyright (c) 2023 marc [marc@lammers.dev](mailto:marc@lammers.dev)" at the end of [README.md](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/blob/master/README.md)
❗ [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 marc [marc@lammers.dev](mailto:marc@lammers.dev)" at the start of LICENSE

**Comment by marc2016** [comment]
Fixed.
