### ISSUE TITLE
Service error: Request failed with status code 401

### ISSUE THREAD

**Issue by ManuelBu96** [marc2016/ioBroker.panasonic-comfort-cloud#49]
**Describe the bug**  
Updated to version 2.2.2, because the API changed on the cloud. After that I only get the error 401. The old version worked before the API in the cloud get updated

**Screenshots & Logfiles**  
Service error: Request failed with status code 401. Code=undefined. Stack: ServiceError: Request failed with status code 401 at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:184:15) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:106:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Versions:**  
 - Adapter version: 2.2.2
 - App API: 1.18.2
 - JS-Controller version: 4.0.23
 - Node version: v12.22.12
 - Operating system: debian

**Comment by ManuelBu96** [comment]
After I reset the password of the account everything works againg as expected.

**Comment by marc2016** [comment]
Please use AppVersion 1.19.1
Automatic update from Github doesn't work.

**Comment by ManuelBu96** [comment]
> Please use AppVersion 1.19.1 Automatic update from Github doesn't work.
I set the AppVersion 1.19.1 and it´s not working @marc2016.

**Comment by marc2016** [comment]
I fixed the bug in loading AppVersion from GitHub. You can try now version 2.2.4.
Please let me know if it works for you :-) Thank you!
