### ISSUE TITLE
Service error: Request failed with status code 401New version app has been published.

### ISSUE THREAD

**Issue by Sansibarr** [marc2016/ioBroker.panasonic-comfort-cloud#56]
Since this morning, i get the known error:
`Service error: Request failed with status code 401New version app has been published. Code=4106. Stack: ServiceError: Request failed with status code 401New version app has been published at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:193:31) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:107:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

--> Newest app version is: 1.20.1 - when you enter this manually in the Instance, the connection works again...

**Comment by superemil70** [comment]
Kann ich bestätigen. Besten Dank für die Info

**Comment by stbe126** [comment]
Ich kann den Fehler ebenfalls bestätigen. Bis 18.03., 1:30 lief der Adapter problemlos.

Vielen Dank für die Mühe!

**Comment by stbe126** [comment]
Die Angabe "Neue Version der App für API" > 1.20.1 

sowie 

deaktivieren des Hakens "Verwenden Sie die von GitHub geladene App-Version" alleine hat bei mir nicht ausgereicht. 

**Ich musste den Nutzernamen und das Passwort erneut identisch eingeben und speichern.**

Momentan läuft die Instanz wieder.

**Comment by bandimuc** [comment]
Der Service war auch bei meiner IOS App gestört und verlangt nun eine MFA Authentifizierung. Ich habe nun auf 2.3.0 upgraded, bekomme bei der App Version aber immer noch 1.19.1 angezeigt ?!?

**Comment by bandimuc** [comment]
Mein aktueller Workaround lautet wie folgt, auf dem Handy / Pad die App aktivieren, das MFA über Handy durchführen, dann Abmelden und ioBroker Adapter mit UID & PW starten. Über den Weg hat es geklappt. Nur die App Version im ioB steht immer noch bei 1.19.1 ??

**Comment by OnkelFD** [comment]
Also ich habe im Adapter einfach 1.20.0 eingegeben und er hat sich verbunden und lässt sich auch ansteuern.

**Comment by poeoe79** [comment]
> Die Angabe "Neue Version der App für API" > 1.20.1
> 
> sowie
> 
> deaktivieren des Hakens "Verwenden Sie die von GitHub geladene App-Version" alleine hat bei mir nicht ausgereicht.
> 
> **Ich musste den Nutzername und das Passwort erneut identisch eingeben und speichern.**
> 
> Momentan läuft die Instanz wieder.

Hallo, das hat bei mir auch funktioniert, danke für die Info!

**Comment by grothauu** [comment]
Bei mir leider nicht. Unabhängig vom gesetzten Haken zieht er nach dem Speichern wieder die 1.19.1. Auch wenn ich links die 1.20.0 oder die 1.20.1 eingebe bisher kein Erfolg. Aber erst mal abwarten.

**Comment by marc2016** [comment]
Vielen Dank, für die vielen Rückmeldungen. Ich habe die Version 1.20.1 auf GitHub ergänzt. Wie @stbe126 schrieb, musste ich das Passwort auch nochmal komplett neu eingeben. Das scheint noch ein Bug zu sein. Prüfe ich.
@grothauu  Funktioniert das bei Dir auch?

**Comment by stbe126** [comment]
Heute musste ich erneut die Anmeldedaten eingeben und speichern. Ebenfalls habe ich den Haken bei "Verwenden Sie die von GitHub geladene App-Version" gesetzt, da nun die korrekte App Version 1.20.1 vorgegeben wird.

**Comment by poeoe79** [comment]
> Vielen Dank, für die vielen Rückmeldungen. Ich habe die Version 1.20.1 auf GitHub ergänzt. Wie @stbe126 schrieb, musste ich das Passwort auch nochmal komplett neu eingeben. Das scheint noch ein Bug zu sein. Prüfe ich. @grothauu Funktioniert das bei Dir auch?

An dieser Stelle nochmal besten Dank! Der Adapter ist bei mir ein essentieller Bestandteil 👍🏻👍🏻

**Comment by superemil70** [comment]
Musste heute auch das Passwort eingeben. Hat tagelang nur mir der Änderung auf 1.20.1 funktioniert
