### ISSUE TITLE
Adapter verbindet sich seit heute nicht mehr

### ISSUE THREAD

**Issue by pioneer01** [marc2016/ioBroker.panasonic-comfort-cloud#59]
Seit heute verbindet sich der Adapter nicht mehr und im Protokoll findet man folgende Einträge:
`Service error: Request failed with status code 403undefined. Code=undefined. Stack: ServiceError: Request failed with status code 403undefined at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:193:31) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:107:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

Die Verbindung ist auch mit diesem Tool (https://github.com/lostfields/python-panasonic-comfort-cloud/tree/master) nicht mehr möglich. Ich denke, dass es ein Update an der API gab, da heute Morgen die offizielle Panasonic App ebenso aufgrund von Wartungsarbeiten kurz nicht funktionierte.

**Comment by tomba0815** [comment]
Bei mir die identische Meldung, Adapter verbindet sich auch nicht mehr

**Comment by role79** [comment]
Bei mir genau so. Meldung analog Ausgangspost.

**Comment by marc2016** [comment]
https://github.com/lostfields/python-panasonic-comfort-cloud/issues/93

**Comment by ManuelBu96** [comment]
> [lostfields/python-panasonic-comfort-cloud#93](https://github.com/lostfields/python-panasonic-comfort-cloud/issues/93)

Ist der Plan die Änderungen auch in diesen Adapter einfließen zu lassen oder eher nicht?

**Comment by marc2016** [comment]
Auf jeden Fall 👍🏻 
Die Anpassung in dem anderen Repository sehen schon sehr gut aus und ich hoffe dieses Wochenende weit komme. Nutze den Adpater auch selbst und will, dass er wieder läuft.

**Comment by poeoe79** [comment]
Danke Marc!

**Comment by marcoschmidt79** [comment]
Im der Homekit-Adapter geht schon wieder.

**Comment by t1m02k16** [comment]
Bei mir ebenfalls wieder down :(

`<html>
<body>

Service error: Request failed with status code 400Missing required header parameter or bad request for header. Code=4000. Stack: ServiceError: Request failed with status code 400Missing required header parameter or bad request for header at new ServiceError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28) at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:193:31) at ComfortCloudClient.<anonymous> (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:228:30) at step (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23) at Object.throw (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53) at rejected (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
--



</body>
</html>`

**Comment by t1m02k16** [comment]
@marc2016 wann können wir mit einem FIX Rechnen? Mir ist warm :D

**Comment by mtb-z** [comment]
Vielen Dank, Marc, dass du dich der Sache annimmst!

**Comment by tomba0815** [comment]
Ebenso von mir vielen Dank, wenn das dann wieder funktioniert warte ich gern noch einige Tage !!!

**Comment by marc2016** [comment]
> @marc2016 wann können wir mit einem FIX Rechnen? Mir ist warm :D

😅 ich arbeite bereits an der Lösung und hoffe, dass ich am Wochenende fertig bin. Andere Projekte haben bereits die Lösung implementiert und ich kann mir den Workflow dort anschauen.

**Comment by marc2016** [comment]
Mit der Version 3.0.0 funktioniert es wieder bei mir. Ich bitte um weitere Tests. App Version habe ich auf 1.21.0 aktualisiert. Falls das nicht automatisch geht, dann bitte manuell eintragen.
https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/releases/tag/v3.0.0

**Comment by MarkX81** [comment]
Danke für deine Mühe. 
Ich habs gerade getestet, aber erhalte diesen Fehler: 

`Unknown error: Error: code is null.. Stack: Error: code is null. at OAuthClient.oAuthProcess (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/OAuthClient.js:65:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:62:27) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)`

**Comment by Scram99** [comment]
Bei mir musste ich das Passwort nochmal eintragen, dann ging es problemlos.

**Comment by poeoe79** [comment]
Danke für die Arbeit!!! Funktioniert wieder. 3.0 installiert Passwort rausgenommenNeustartPasswort reinNeustartLäuft 💪🎉🎉Mit freundlichen GrüßenJens Pöggeler Am 29.06.24 um 14:02 schrieb MarkX81
                
            
            
                
                    Von: "MarkX81" ***@***.***>Datum: 29. Juni 2024An: "marc2016/ioBroker.panasonic-comfort-cloud" ***@***.***>Cc: "poeoe79" ***@***.***>,"Comment" ***@***.***>Betreff: Re: [marc2016/ioBroker.panasonic-comfort-cloud] Adapter verbindet sich seit heute nicht mehr (Issue #59)
                
                
Danke für deine Mühe.
Ich habs gerade getestet, aber erhalte diesen Fehler:
Unknown error: Error: code is null.. Stack: Error: code is null. at OAuthClient.oAuthProcess (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/OAuthClient.js:65:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:62:27) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)

**Comment by t1m02k16** [comment]
Läuft vielen Dank @marc2016

**Comment by marc2016** [comment]
Ich habe den refresh des Token vergessen. Kümmere ich mich morgen Abend drum…

**Comment by pioneer01** [comment]
Danke für deine Arbeit! Bei mir funktioniert es auch nachdem ich das so gemacht habe:

> Danke für die Arbeit!!! Funktioniert wieder. 3.0 installiert Passwort rausgenommenNeustartPasswort reinNeustartLäuft 💪🎉🎉Mit freundlichen GrüßenJens Pöggeler Am 29.06.24 um 14:02 schrieb MarkX81 Von: "MarkX81" ***@***.***>Datum: 29. Juni 2024An: "marc2016/ioBroker.panasonic-comfort-cloud" ***@***.***>Cc: "poeoe79" ***@***.***>,"Comment" ***@***.***>Betreff: Re: [marc2016/ioBroker.panasonic-comfort-cloud] Adapter verbindet sich seit heute nicht mehr (Issue #59) Danke für deine Mühe. Ich habs gerade getestet, aber erhalte diesen Fehler: Unknown error: Error: code is null.. Stack: Error: code is null. at OAuthClient.oAuthProcess (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/OAuthClient.js:65:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:62:27) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by superemil70** [comment]
Bekomme es leider nicht zum laufen mit der 3.0. Habe den adapter auch mal komplett gelöscht und neu aufgespielt. Gleichers Problem. Was ich vorher nicht hatte
`Unknown error: Error: code is null.. Stack: Error: code is null. at OAuthClient.oAuthProcess (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/OAuthClient.js:65:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:62:27) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)`

Woran liegt das jetzt?

**Comment by mtb-z** [comment]
Bei mir funktioniert es jetzt einwandfrei. Vielen Dank, Marc

**Comment by poeoe79** [comment]
So wie ich das verstanden hab fehlt noch was.Die Token laufen aus und müssen erneuert werden.Marc ist aber glaub dran 👍🏻👍🏻Mit freundlichen GrüßenJens Pöggeler Am 01.07.24 um 18:43 schrieb superemil70
                
            
            
                
                    Von: "superemil70" ***@***.***>Datum: 1. Juli 2024An: "marc2016/ioBroker.panasonic-comfort-cloud" ***@***.***>Cc: "poeoe79" ***@***.***>,"Comment" ***@***.***>Betreff: Re: [marc2016/ioBroker.panasonic-comfort-cloud] Adapter verbindet sich seit heute nicht mehr (Issue #59)
                
                
Bekomme es leider nicht zum laufen mit der 3.0. Habe den adapter auch mal komplett gelöscht und neu aufgespielt. Gleichers Problem. Was ich vorher nicht hatte
Unknown error: Error: code is null.. Stack: Error: code is null. at OAuthClient.oAuthProcess (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/OAuthClient.js:65:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:62:27) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)
Woran liegt das jetzt?

**Comment by tomba0815** [comment]
Ja, und so lange reicht es im Adapter das Passwort zu löschen, dann speichern und danach das Passwort nochmals eingeben und speichern.

**Comment by gallersd** [comment]
Bei mir funktioniert es jetzt auch wieder. Vielen Dank, Marc

**Comment by pioneer01** [comment]
Bei mir funktionierts auch wieder perfekt. Mit Hilfe des Adapters wird die Klimaanlage an die aktuelle Leistung vom Balkonkraftwerk angepasst:
![Bildschirmfoto_2024-07-03_14-47-47](https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/assets/29012089/3fb51394-8687-4211-8219-e30a512290d9)

**Comment by poeoe79** [comment]
Hey, coole Idee. Wie machst du das? Kann man die pana in der stromaufnahme begrenzen? Hab ich das übersehen?Mit freundlichen GrüßenJens Pöggeler Am 03.07.24 um 14:49 schrieb pioneer01
                
            
            
                
                    Von: "pioneer01" ***@***.***>Datum: 3. Juli 2024An: "marc2016/ioBroker.panasonic-comfort-cloud" ***@***.***>Cc: "poeoe79" ***@***.***>,"Comment" ***@***.***>Betreff: Re: [marc2016/ioBroker.panasonic-comfort-cloud] Adapter verbindet sich seit heute nicht mehr (Issue #59)
                
                
Bei mir funktionierts auch wieder perfekt. Mit Hilfe des Adapters wird die Klimaanlage an die aktuelle Leistung vom Balkonkraftwerk angepasst:
Bildschirmfoto_2024-07-03_14-47-47.jpg (view on web)

**Comment by pioneer01** [comment]
Die Stromaufnahme kannst du leider nicht begrenzen, aber du kannst die Soll-Temperatur als Stellgröße nehmen. Wenn mehr eingespeist wird -> Soll-Temperatur runter, bei Bezug aus dem Stromnetz -> Soll-Temperatur rauf. Dadruch, dass es sich um Inverter Geräte handelt, funktioniert das einigermaßen gut.

**Comment by pioneer01** [comment]
Ich habe Version 3.0.1 installiert. Hier sollte der auth token ja laut changelog schon gefixed sein, oder? Adapter war heute nicht verbunden und ich hatte folgenden Eintrag im Log:
`Service error: Request failed with status code 401Token expires. Code=4100. Stack: ServiceError: Request failed with status code 401Token expires at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31) at ComfortCloudClient.getGroups (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:107:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.refreshDevices (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:176:22) at async PanasonicComfortCloud.refreshTimeoutFunc (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:544:7)`

Nachdem ich den Adapter einmal neu gestartet habe, hat es wieder funktioniert.

**Comment by marc2016** [comment]
Ich musste leider auch heute Morgen feststellen, dass das noch nicht richtig funktioniert. Ich schaue mir das heute Abend an.

**Comment by kdtcat** [comment]
> _Nachdem ich den Adapter einmal neu gestartet habe, hat es wieder funktioniert._

Wenn ich "automatische Updates"   einrichte, kommt der Token Fehler nach einer gewissen Zahl an Updates. :-(

**Comment by pioneer01** [comment]
> Ich musste leider auch heute Morgen feststellen, dass das noch nicht richtig funktioniert. Ich schaue mir das heute Abend an.

Alles klar, kein Stress. Wollte es nur gemeldet haben. Danke!

**Comment by marc2016** [comment]
> > _Nachdem ich den Adapter einmal neu gestartet habe, hat es wieder funktioniert._
> 
> Wenn ich "automatische Updates" einrichte, kommt der Token Fehler nach einer gewissen Zahl an Updates. :-(

Sollte jetzt aber wieder gehen. Sonst bitte einen neuen issue erstellen.

**Comment by kdtcat** [comment]
Ja super. automatische Updates läuft wieder ohne Probleme. Vielen Dank für Deine Arbeit.

**Comment by pioneer01** [comment]
Heute war der Adapter seit langer Zeit wieder einmal nicht verbunden. Eintrag im Log:
`Service error: Request failed with status code 401Token expires. Code=4100. Stack: ServiceError: Request failed with status code 401Token expires at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31) at ComfortCloudClient.setParameters (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:173:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.updateDevice (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:433:9) at async PanasonicComfortCloud.onStateChange (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:482:9)`

Als Workaround starte ich den Adapter nun mal per Cronjob täglich neu:
0 0 * * * iobroker restart panasonic-comfort-cloud.0

**Comment by balu1967** [comment]
funktioniert es bei euch immer noch? Ich krieg ne Fehlermeldung

**Comment by Scram99** [comment]
Hm. Funktioniert bei mir.

**Comment by balu1967** [comment]
welche Versionsnummer hast du hier eingestellt?
![image](https://github.com/user-attachments/assets/435914bf-6e30-41ee-91ce-8b747a9dcdd1)

**Comment by Scram99** [comment]
Genau diese.

**Comment by MarkX81** [comment]
Man muss die neue Version manuell installieren als Experte. Wenn ich es als Update installiere kommt ein Fehler 

Hier der Link:
`https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/archive/refs/tags/v3.0.3.tar.gz`

Danach noch die Version 1.22.0 eintragen und es sollte wieder funktionieren :)

**Comment by balu1967** [comment]
ja hab ich beides gemacht
![image](https://github.com/user-attachments/assets/23026a80-b93d-46f8-a1e3-9fc02f5dcb04)

Leider kommt dann die Fehlermeldung

![image](https://github.com/user-attachments/assets/ec1086b7-09d5-4765-a2c6-62a966513435)

**Comment by balu1967** [comment]
nein, der Haken ist drin. Ich nutze doch mit der 3.0.3 die Git-Hub - Version?

**Comment by Scram99** [comment]
1.22.0 manuell

**Comment by balu1967** [comment]
Danke euch, jetzt klappts wieder :-)
