### ISSUE TITLE
err: status code 401New version app has been published

### ISSUE THREAD

**Issue by WilliLz** [marc2016/ioBroker.panasonic-comfort-cloud#66]
since this morming I get following error:
	Service error: Request failed with status code 401New version app has been published. Code=4106. Stack: ServiceError: Request failed with status code 401New version app has been published at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31) at ComfortCloudClient.getGroups (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:107:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.refreshDevices (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:176:22) at async PanasonicComfortCloud.refreshTimeoutFunc (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:544:7)

**Comment by superemil70** [comment]
Kann ich bestätigen. Bekomme die Meldung auch

panasonic-comfort-cloud.0
	2024-11-06 20:37:21.466	error	Service error: Request failed with status code 401 New version app has been published. 
	Code=4106. Stack: ServiceError: Request failed with status code 401 New version app has been published at ComfortCloudClient.handleError
	(/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31) 
	at ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:66:18) 
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.onReady 
	(/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)

**Comment by marc2016** [comment]
https://github.com/sockless-coding/panasonic_cc/issues/331

**Comment by marc2016** [comment]
Working again with 3.0.3
