### ISSUE TITLE
Error in iobroker log: New version app has been published. Code=4106

### ISSUE THREAD

**Issue by Joschi24** [marc2016/ioBroker.panasonic-comfort-cloud#67]
The following error came up in the morning:

Service error: Request failed with status code 401 New version app has been published. Code=4106. Stack: ServiceError: Request failed with status code 401 New version app has been published at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31) at ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:66:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)

I tried to changed the API App Version in the config to  1.22.0. The error is now:

Service error: Request failed with status code 412 Precondition Failed. Code=41201. Stack: ServiceError: Request failed with status code 412 Precondition Failed at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31) at ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:66:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)

I would be very grateful if you could fix it because I use this adapter to control the air conditioning so that it doesn't cycle so often.

**Comment by Sansibarr** [comment]
Good morning, 
exactly same issue and error message on my side (after manually changing version number to 1.22.0).
Would be awesome, when someone could check this...

Many thanks!

**Comment by marc2016** [comment]
https://github.com/sockless-coding/panasonic_cc/issues/331

**Comment by Olifant1990** [comment]
Solved with https://github.com/sockless-coding/panasonic_cc/pull/336.
I can confirm it is working again!

**Comment by marc2016** [comment]
Working again with 3.0.3
