### ISSUE TITLE
Can't update to 3.0.3

### ISSUE THREAD

**Issue by tobstare** [marc2016/ioBroker.panasonic-comfort-cloud#69]
**Describe the bug**  
Can't update to 3.0.3. With 3.0.2 i get status code error 401.

**To Reproduce**  
1. Go to 'Adapter'
2. Click on 'Install specific version'
![image](https://github.com/user-attachments/assets/f415806f-81f5-40fe-ab19-e326f4fec9ec)

4. Click on 3.0.3
5. See error:
![image](https://github.com/user-attachments/assets/7eb4d3e5-157e-4eea-b4d7-2305b187384e)

**Versions:**  
 - Adapter version: 3.0.2
 - JS-Controller version: 7.0.2 
 - Node version: 20.18.0 
 - Operating system: docker (official image - v10.0.0)

There is a changelog entry for 3.0.3:
![image](https://github.com/user-attachments/assets/bd25420a-f9a9-4aa6-8a40-ec2c1ab9db6b)

But no Release for it:
![image](https://github.com/user-attachments/assets/d05756aa-e9fb-44fd-8eb5-0d0458563e51)

**Comment by MarkX81** [comment]
Hatte das gleiche Problem, aber du kannst es als Experte Manuell installieren. 

`https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/archive/refs/tags/v3.0.3.tar.gz`

**Comment by mcm1957** [comment]
**Eine Version 3.0.3 EXISTIERT NICHT**

Der Bauvorgang dieser Version ist schief gegangen und diese Version steht auf npm nicht zur Verfügung. Die Anzeige in Admin ist hier leider FALSCH.

Von einer Installation von Github wird dringend abgeraten da der Softwarestand auf Github nicht einer Version zugeordent werden kann und möglicherweise fehlerhaft ist - sonst wäre der Bauvorgang wohl nicht schief gegangen

**Comment by mcm1957** [comment]
> Hatte das gleiche Problem, aber du kannst es als Experte Manuell installieren.
> 
> `https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/archive/refs/tags/v3.0.3.tar.gz`

Ohne Anweisung des Dev NIEMALS direkt von Github installieren!

Und deine Anweisung ist mehr als risky. Der Bauvorgang der 3.0.3 ist schief gegangen. Sonst wäre die Version sauber auf npm verfügbar. Devon  einen User auf einen unklaren Github Stand zu verweisen ist dringend abzuraten !

**Comment by marc2016** [comment]
Sorry, bei meinem release ist irgendwas schiefgegangen :-( Sollte jetzt aber alle korrekt laufen, wenn der PR durch ist https://github.com/ioBroker/ioBroker.repositories/pull/4319
Ging leider bei mir nicht schneller, konnte mich jetzt erst drum kümmern... :-(

**Comment by DevForGit** [comment]
Hallo Marc,
danke für Deine tolle Arbeit.Ich wünsche Dir noch eine besinnliche Weihnachtszeit.
 
Viele GrüßeKalle
 


Gesendet: Montag, 25. November 2024 um 21:09
Von: marc2016 ***@***.***>
An: "marc2016/ioBroker.panasonic-comfort-cloud" ***@***.***>
CC: DevForGit ***@***.***>,Comment ***@***.***>
Betreff: Re: [marc2016/ioBroker.panasonic-comfort-cloud] Can't update to 3.0.3 (Issue #69)

 
Sorry, bei meinem release ist irgendwas schiefgegangen :-( Sollte jetzt aber alle korrekt laufen, wenn der PR durch ist ioBroker/ioBroker.repositories#4319Ging leider bei mir nicht schneller, konnte mich jetzt erst drum kümmern... :-(
