### ISSUE TITLE
Please add "insideTemperature", "outTemperature" and "nanoe"

### ISSUE THREAD

**Issue by mule1972** [marc2016/ioBroker.panasonic-comfort-cloud#7]
First i would like to thank you for this great iobroker adapter!

I would be very thankful if you could add "insideTemperature", "outTemperature" and "nanoe" to your adapter.

**Comment by marc2016** [comment]
You are welcome!
Added in Version 1.2.1 :-)

**Comment by mule1972** [comment]
The new version is working fine. Thanks for adding those features!
