### ISSUE TITLE
IMPORTANT: Please fix build of release 3.0.3 (or newer)

### ISSUE THREAD

**Issue by mcm1957** [marc2016/ioBroker.panasonic-comfort-cloud#70]
Build of Release 3.03 failed. This release is not deployed to npm nor created at github.

Please check and fix either build / deploy of 3.0.3 or create a new release so that your last fixes become available to users.

**Comment by marc2016** [comment]
Everything should be correct now https://github.com/ioBroker/ioBroker.repositories/pull/4319
Sorry for the delay, a little stress at work :-(
