### ISSUE TITLE
Nicht verbunden mit Gerät oder Dienst

### ISSUE THREAD

**Issue by neolight1302** [marc2016/ioBroker.panasonic-comfort-cloud#72]
Auf Wunsch ein neues Issue zum alten Problem. 

Der Adapter verbindet sich nicht. 

Adapterversion: 3.0.2

Fehlermeldung:

Service error: Request failed with status code 412 Precondition Failed. Code=41201. Stack: ServiceError: Request failed with status code 412 Precondition Failed at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31) at ComfortCloudClient.setParameters (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:173:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.updateDevice (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:433:9) at async PanasonicComfortCloud.onStateChange (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:482:9)

**Comment by mcm1957** [comment]
Please check with up to date release: 3.0.3

**Comment by Crazyachmed** [comment]
Funktioniert noch nicht:

`Service error: Request failed with status code 401New version app has been published. Code=4106. Stack: ServiceError: Request failed with status code 401New version app has been published at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:149:31) at ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:68:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)`

Adapter mit Version 3.0.3, Option App-Version von Git-Hub gesetzt (1.21.0)

**Comment by neolight1302** [comment]
Versuch mal die App Version händisch auf 1.22.0 zu setzen. So geht es bei mir jetzt.

**Comment by Crazyachmed** [comment]
Das geht, kannst du das bitte anpassen?

PS: Es gab eine große Menge Log-Meldungen dieser Art: `Method "createState" is deprecated and will be removed in js-controller 7.1, use "extendObject/setObjectNotExists" instead`

**Comment by neolight1302** [comment]
Was soll ich anpassen?

**Comment by Crazyachmed** [comment]
Der Adapter lädt von GitHub die zu verwendende Version gegenüber der API, die, die ich jetzt von Hand angepasst habe. Die stand bei meinem Versuch gerade noch auf 1.21.0. Dann müssen die anderen Leute das nicht von Hand anpassen.

**Comment by neolight1302** [comment]
Fein, aber ich bin doch gar nicht der Entwickler! ;-)

**Comment by Crazyachmed** [comment]
Ach, hab ich nicht gesehen.

In der Datei steht auch schon 1.22.0 seit drei Wochen, trotzdem hab ich `Loaded app version from GitHub: 1.21.0`
